// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/access/AccessControl.sol";
import "./IVerifier.sol";

contract Election is AccessControl {
    bytes32 public constant ELECTION_MANAGER_ROLE = keccak256("ELECTION_MANAGER_ROLE");

    IVerifier public zkpVerifier;

    enum ElectionState { NotStarted, Ongoing, Ended }
    ElectionState public state;

    struct Candidate {
        uint256 id;
        string name;
        string imageCID;
        uint256 voteCount;
    }

    mapping(uint256 => Candidate) public candidates;
    uint256 public candidatesCount;

    // ZKP Nullifiers (prevents double voting without revealing identity)
    mapping(uint256 => bool) public nullifiers;
    uint256 public totalVotes;

    event CandidateAdded(uint256 indexed candidateId, string name, string imageCID);
    event VoteCasted(uint256 nullifierHash, uint256 indexed candidateId);
    event ElectionStateChanged(ElectionState newState);

    constructor(address _verifierAddress) {
        _grantRole(DEFAULT_ADMIN_ROLE, msg.sender);
        _grantRole(ELECTION_MANAGER_ROLE, msg.sender);
        zkpVerifier = IVerifier(_verifierAddress);
        state = ElectionState.NotStarted;
    }

    modifier inState(ElectionState _state) {
        require(state == _state, "Invalid election state for this action");
        _;
    }

    function addCandidate(string memory _name, string memory _imageCID) 
        external 
        onlyRole(ELECTION_MANAGER_ROLE) 
        inState(ElectionState.NotStarted) 
    {
        candidatesCount++;
        candidates[candidatesCount] = Candidate({
            id: candidatesCount,
            name: _name,
            imageCID: _imageCID,
            voteCount: 0
        });
        emit CandidateAdded(candidatesCount, _name, _imageCID);
    }

    function startElection() external onlyRole(ELECTION_MANAGER_ROLE) inState(ElectionState.NotStarted) {
        state = ElectionState.Ongoing;
        emit ElectionStateChanged(state);
    }

    function endElection() external onlyRole(ELECTION_MANAGER_ROLE) inState(ElectionState.Ongoing) {
        state = ElectionState.Ended;
        emit ElectionStateChanged(state);
    }

    // New ZKP-enabled Vote function
    function vote(
        uint256 _candidateId,
        uint[2] memory a,
        uint[2][2] memory b,
        uint[2] memory c,
        uint256 nullifierHash
    ) external inState(ElectionState.Ongoing) {
        require(_candidateId > 0 && _candidateId <= candidatesCount, "Invalid candidate ID");
        require(!nullifiers[nullifierHash], "Voter has already voted (Nullifier used)");

        // Prepare the public inputs for the ZKP Verifier (nullifierHash is public)
        uint[1] memory publicInputs = [nullifierHash];

        // Verify the zk-SNARK proof!
        // If this returns true, the voter is verified to have a valid Aadhaar JWT off-chain.
        // We use an external Verifier contract generated by SnarkJS.
        require(zkpVerifier.verifyProof(a, b, c, publicInputs), "Invalid Zero Knowledge Proof");

        // Record the nullifier so this proof can't be reused
        nullifiers[nullifierHash] = true;

        // Tally the vote
        candidates[_candidateId].voteCount++;
        totalVotes++;

        // Notice msg.sender is completely disassociated from the identity. 
        // Complete privacy!
        emit VoteCasted(nullifierHash, _candidateId);
    }

    function getCandidate(uint256 _candidateId) external view returns (Candidate memory) {
        require(_candidateId > 0 && _candidateId <= candidatesCount, "Invalid candidate ID");
        return candidates[_candidateId];
    }
}
