const { ethers, network, artifacts } = require("hardhat");
const fs = require("fs");
const path = require("path");

// Paths
const FRONTEND_ENV = path.resolve(__dirname, "../../frontend/.env.local");
const FRONTEND_CONTRACTS = path.resolve(__dirname, "../../frontend/src/contracts");

async function main() {
    const [deployer] = await ethers.getSigners();
    console.log("══════════════════════════════════════════════");
    console.log("  Deploying E-Voting System Contracts");
    console.log("══════════════════════════════════════════════");
    console.log("Network:         ", network.name);
    console.log("Deployer address:", deployer.address);
    console.log("");

    // ─────────────────────────────────────────────
    // 1. Deploy VoterSBT
    // ─────────────────────────────────────────────
    console.log("[1/4] Deploying VoterSBT...");
    const VoterSBT = await ethers.getContractFactory("VoterSBT");
    const voterSBT = await VoterSBT.deploy();
    await voterSBT.waitForDeployment();
    const sbtAddress = await voterSBT.getAddress();
    console.log("  ✓ VoterSBT deployed to:", sbtAddress);

    // ─────────────────────────────────────────────
    // 2. Deploy TimelockController
    // ─────────────────────────────────────────────
    console.log("[2/4] Deploying TimelockController...");
    const MIN_DELAY = 60;
    const proposers = [deployer.address];
    const executors = [deployer.address];
    const admin = deployer.address;

    const TimelockController = await ethers.getContractFactory("TimelockController");
    const timelock = await TimelockController.deploy(MIN_DELAY, proposers, executors, admin);
    await timelock.waitForDeployment();
    const timelockAddress = await timelock.getAddress();
    console.log("  ✓ TimelockController deployed to:", timelockAddress);

    // ─────────────────────────────────────────────
    // 3. Deploy Election
    // ─────────────────────────────────────────────
    console.log("[3/4] Deploying Election...");
    const Election = await ethers.getContractFactory("Election");
    const election = await Election.deploy(sbtAddress);
    await election.waitForDeployment();
    const electionAddress = await election.getAddress();
    console.log("  ✓ Election deployed to:", electionAddress);

    // ─────────────────────────────────────────────
    // 4. Configure Roles
    // ─────────────────────────────────────────────
    console.log("[4/4] Configuring roles...");
    const TIMELOCK_ROLE = await election.TIMELOCK_ROLE();
    await election.grantRole(TIMELOCK_ROLE, timelockAddress);
    console.log("  ✓ Granted TIMELOCK_ROLE to TimelockController");

    const isLocal = network.name === "localhost" || network.name === "hardhat";
    if (isLocal) {
        await election.grantRole(TIMELOCK_ROLE, deployer.address);
        console.log("  ✓ Granted TIMELOCK_ROLE to deployer (LOCAL TESTING ONLY)");
    }

    // ─────────────────────────────────────────────
    // 5. Auto-write frontend/.env.local
    // ─────────────────────────────────────────────
    console.log("\n[AUTO] Writing addresses to frontend/.env.local ...");
    const envContent = `# Auto-generated by deploy.js — ${new Date().toISOString()}
# Network: ${network.name}
NEXT_PUBLIC_ELECTION_CONTRACT_ADDRESS="${electionAddress}"
NEXT_PUBLIC_VOTER_SBT_ADDRESS="${sbtAddress}"
NEXT_PUBLIC_TIMELOCK_ADDRESS="${timelockAddress}"

# Backend API
NEXT_PUBLIC_BACKEND_URL="http://localhost:3001"
`;
    fs.writeFileSync(FRONTEND_ENV, envContent, "utf8");
    console.log("  ✓ Wrote frontend/.env.local");

    // ─────────────────────────────────────────────
    // 6. Copy ABI artifacts to frontend/src/contracts
    // ─────────────────────────────────────────────
    console.log("[AUTO] Copying ABI artifacts to frontend/src/contracts ...");
    fs.mkdirSync(FRONTEND_CONTRACTS, { recursive: true });

    const electionArtifact = await artifacts.readArtifact("Election");
    fs.writeFileSync(
        path.join(FRONTEND_CONTRACTS, "ElectionABI.json"),
        JSON.stringify(electionArtifact.abi, null, 2),
        "utf8"
    );
    console.log("  ✓ ElectionABI.json updated");

    const sbtArtifact = await artifacts.readArtifact("VoterSBT");
    fs.writeFileSync(
        path.join(FRONTEND_CONTRACTS, "VoterSBTABI.json"),
        JSON.stringify(sbtArtifact.abi, null, 2),
        "utf8"
    );
    console.log("  ✓ VoterSBTABI.json updated");

    // ─────────────────────────────────────────────
    // Summary
    // ─────────────────────────────────────────────
    console.log("");
    console.log("══════════════════════════════════════════════");
    console.log("  ✅ Deployment Complete!");
    console.log("══════════════════════════════════════════════");
    console.log("");
    console.log("  VoterSBT:           ", sbtAddress);
    console.log("  TimelockController: ", timelockAddress);
    console.log("  Election:           ", electionAddress);
    console.log("");
    console.log("  ✓ frontend/.env.local   — updated automatically");
    console.log("  ✓ frontend/src/contracts — ABIs updated");
    console.log("");
    console.log("  ➜ Start frontend: cd ../frontend && npm run dev");
    console.log("");
}

main()
    .then(() => process.exit(0))
    .catch((error) => {
        console.error(error);
        process.exit(1);
    });
